CREATE DATABASE ACTIVIDAD1;
GO
USE ACTIVIDAD1;
GO

CREATE TABLE ESTUDIANTES(
    IDESTUDIANTE BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    APELLIDOS VARCHAR(100) NOT NULL,
    NOMBRES VARCHAR(100) NOT NULL,
    FECHANACIMIENTO DATE NOT NULL,
    FECHAINGRESO DATE NOT NULL DEFAULT(GETDATE())

)
GO
CREATE TABLE TIPOINSTRUMENTOS(
    IDTIPOINSTRUMENTO TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    NOMBRETIPO VARCHAR(50) NOT NULL,

)
GO

CREATE TABLE INSTRUMENTOS(
    IDINSTRUMENTOS SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL,
    IDTIPOINSTRUMENTO TINYINT NULL FOREIGN KEY REFERENCES TIPOINSTRUMENTOS(IDTIPOINSTRUMENTO),
    CODIGO VARCHAR(10) NOT NULL UNIQUE

)

GO

CREATE TABLE INSTUMENTO_x_ESTUDIANTE(
    IDESTUDIANTE BIGINT NOT NULL FOREIGN KEY REFERENCES ESTUDIANTES(IDESTUDIANTE),
    IDINSTRUMENTO SMALLINT NOT NULL FOREIGN KEY REFERENCES INSTUMENTOS(IDINSTRUMENTO),
    PRIMARY KEY (IDESTUDIANTE, IDINSTRUMENTO)

)

